# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('course_credits', models.IntegerField(max_length=10)),
                ('prereq_courses', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Professor', models.CharField(max_length=100)),
                ('Semester_offered', models.IntegerField(max_length=10)),
                ('Offered_year', models.IntegerField(max_length=10)),
            ],
        ),
    ]
