# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Semester_offered',
            field=models.IntegerField(default=0),
        ),
    ]
