# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180308_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('course_credits', models.IntegerField(default=0)),
                ('prereq_courses', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Offered_year',
            field=models.IntegerField(default=0),
        ),
    ]
