# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_precourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precourses',
            name='pre_course',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Semester_offered',
        ),
        migrations.AddField(
            model_name='reviews',
            name='Review',
            field=models.CharField(default='NULL', max_length=3000),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Semester',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='reviews',
            name='ccode',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Professor',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.DeleteModel(
            name='PreCourses',
        ),
    ]
