# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180311_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ccode',
        ),
    ]
