# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_reviews_ccode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Offered_year',
            new_name='offered_year',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Professor',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Semester',
            new_name='semester',
        ),
    ]
