# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180312_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ccode',
        ),
    ]
