# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_reviews_ccode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='career_field',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
