# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_career_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(default=0)),
                ('Remark', models.CharField(default='NULL', max_length=200)),
                ('slot', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
