# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180325_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_field', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='career_field',
        ),
    ]
