# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180325_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag',
        ),
        migrations.AddField(
            model_name='course',
            name='career_field',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
