# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180325_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_slot',
            name='slot',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='ccode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.DeleteModel(
            name='Time_slot',
        ),
    ]
