# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20180325_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ccode',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
