# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20180325_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ccode',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
