# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20180327_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='career_field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereq_courses',
            field=models.CharField(max_length=100),
        ),
    ]
