# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 16:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20180426_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='career_field',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereq_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
