# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20180426_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prereq_courses',
        ),
    ]
