# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 16:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20180426_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prereq_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='NULL', max_length=200), blank=True, size=None),
        ),
    ]
