# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20180426_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='career_field',
            field=models.CharField(max_length=100),
        ),
    ]
